apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: supply-chain
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - port: 3007
    targetPort: 3007
    nodePort: 31007
    protocol: TCP
    name: http
