apiVersion: v1
kind: Service
metadata:
  name: contract-service
  namespace: supply-chain
  labels:
    app: contract-service
spec:
  type: NodePort
  selector:
    app: contract-service
  ports:
  - port: 3006
    targetPort: 3006
    nodePort: 31006
    protocol: TCP
    name: http
