apiVersion: v1
kind: Service
metadata:
  name: crm-service
  namespace: supply-chain
  labels:
    app: crm-service
spec:
  type: NodePort
  selector:
    app: crm-service
  ports:
  - port: 3019
    targetPort: 3019
    nodePort: 31019
    protocol: TCP
    name: http
