apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: supply-chain
  labels:
    app: profile-service
spec:
  type: NodePort
  selector:
    app: profile-service
  ports:
  - port: 3018
    targetPort: 3018
    nodePort: 31018
    protocol: TCP
    name: http
