apiVersion: v1
kind: Service
metadata:
  name: seller-binding-service
  namespace: supply-chain
  labels:
    app: seller-binding-service
spec:
  type: NodePort
  selector:
    app: seller-binding-service
  ports:
  - port: 3013
    targetPort: 3013
    nodePort: 31013
    protocol: TCP
    name: http
