apiVersion: v1
kind: Service
metadata:
  name: price-service
  namespace: supply-chain
  labels:
    app: price-service
spec:
  type: NodePort
  selector:
    app: price-service
  ports:
    - name: http
      port: 3009
      targetPort: 3009
      nodePort: 31009
