apiVersion: v1
kind: Service
metadata:
  name: publish-service
  namespace: supply-chain
  labels:
    app: publish-service
spec:
  type: NodePort
  selector:
    app: publish-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005
      nodePort: 31005
