apiVersion: v1
kind: ConfigMap
metadata:
  name: supply-chain-common
  namespace: supply-chain
data:
  PG_HOST: "100.67.126.90"
  PG_PORT: "5432"
  PG_DATABASE: "supply_chain"
  PG_USER: "postgres"
  MONGODB_URI: "mongodb://100.67.126.90:27017,supply-chain"
  REDIS_URI: "redis://100.96.54.109:6379/0"
  MINIO_ENDPOINT: "100.96.54.109:9000"
