apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-list-service
  namespace: supply-chain
spec:
  replicas: 1
  selector: { matchLabels: { app: purchase-list-service } }
  template:
    metadata: { labels: { app: purchase-list-service } }
    spec:
      nodeSelector:
        kubernetes.io/hostname: huangfra-ubun-master-ms-7e11
      containers:
        - name: purchase-list-service
          image: 100.76.15.64:5001/supply-chain/purchase-list-service:latest
          imagePullPolicy: Always
          ports: [ { containerPort: 3013 } ]
          envFrom:
            - configMapRef: { name: supply-chain-common }
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-list-service
  namespace: supply-chain
spec:
  type: NodePort
  selector: { app: purchase-list-service }
  ports:
    - port: 3013
      targetPort: 3013
      nodePort: 31015
