apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: supply-chain
  labels:
    app: profile-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: huangfra-ubun-master-ms-7e11
      containers:
      - name: profile-service
        image: 100.96.54.109:5001/supply-chain/profile-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3018
        envFrom:
        - configMapRef:
            name: supply-chain-common
        - secretRef:
            name: supply-chain-secrets
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3018"
        resources:
          requests:
            cpu: 50m
            memory: 96Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3018
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3018
          initialDelaySeconds: 3
          periodSeconds: 10
