apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  namespace: supply-chain
  labels:
    app: supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: huangfra-ubun-master-ms-7e11
      containers:
      - name: supplier-service
        image: 100.76.15.64:5001/supply-chain/supplier-service:latest
        imagePullPolicy: Always
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: supply-chain-common
        - secretRef:
            name: supply-chain-secrets
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: NEW_ECOMMERCE_PG_DATABASE
          value: "new_ecommerce"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3002
          initialDelaySeconds: 3
          periodSeconds: 10
