[sudo] password for huangfra-ubun-master: apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    archive.date: "2026-07-15"
    archive.reason: replaced-by-product-api-service (PG). Do not scale back.
    deployment.kubernetes.io/revision: "63"
    field.cattle.io/publicEndpoints: '[{"port":31099,"protocol":"TCP","serviceName":"supply-chain:product-service","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"product-service"},"name":"product-service","namespace":"supply-chain"},"spec":{"replicas":0,"selector":{"matchLabels":{"app":"product-service"}},"template":{"metadata":{"labels":{"app":"product-service"}},"spec":{"containers":[{"command":["sh","-lc","cd /app/backend \u0026\u0026 node server.js"],"env":[{"name":"NODE_ENV","value":"production"},{"name":"PORT","value":"3000"},{"name":"MONGODB_URI","valueFrom":{"secretKeyRef":{"key":"MONGODB_URI","name":"product-mongo-env"}}},{"name":"MONGODB_URI_FALLBACK","valueFrom":{"secretKeyRef":{"key":"MONGODB_URI_FALLBACK","name":"product-mongo-env"}}}],"envFrom":[{"configMapRef":{"name":"supply-chain-common"}}],"image":"100.76.15.64:5001/supply-chain/product-service:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/api/health","port":3000},"initialDelaySeconds":10,"periodSeconds":30},"name":"product-service","ports":[{"containerPort":3000}],"readinessProbe":{"httpGet":{"path":"/api/health","port":3000},"initialDelaySeconds":3,"periodSeconds":10},"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"nodeSelector":{"kubernetes.io/hostname":"huangfra-ubun-master-ms-7e11"}}}}}
  creationTimestamp: "2026-07-01T08:50:06Z"
  generation: 68
  labels:
    app: product-service
  name: product-service
  namespace: supply-chain
  resourceVersion: "176809711"
  uid: b132bda8-cdf0-4c5c-9579-03d88696467b
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-16T07:14:47+08:00"
      creationTimestamp: null
      labels:
        app: product-service
    spec:
      containers:
      - command:
        - sh
        - -lc
        - cd /app/backend && node server.js
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: MONGODB_URI
              name: product-mongo-env
        - name: MONGODB_URI_FALLBACK
          valueFrom:
            secretKeyRef:
              key: MONGODB_URI_FALLBACK
              name: product-mongo-env
        envFrom:
        - configMapRef:
            name: supply-chain-common
        image: 100.76.15.64:5001/supply-chain/product-service:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: product-service
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: huangfra-ubun-master-ms-7e11
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-07-01T09:03:22Z"
    lastUpdateTime: "2026-07-01T09:03:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-07-01T08:50:06Z"
    lastUpdateTime: "2026-07-15T23:14:50Z"
    message: ReplicaSet "product-service-6947b867ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 68
