user nginx;
worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 1024;
}

http {
    client_body_timeout 300s;

    client_max_body_size 50m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_connect_timeout 60s;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    # product-service -> k3s NodePort 31001 (service port 3000)
    upstream product-service {
        server 100.96.54.109:31001;
    }
    server {
        listen 3001;
        location / {
            proxy_pass http://product-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # supplier-service -> k3s NodePort 31002 (service port 3002)
    upstream supplier-service {
        server 100.96.54.109:31002;
    }
    server {
        listen 3002;
        location / {
            proxy_pass http://supplier-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # shop-service -> k3s NodePort 31004 (service port 3004)
    upstream shop-service {
        server 100.96.54.109:31004;
    }
    server {
        listen 3004;
        location / {
            proxy_pass http://shop-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # order-service -> k3s NodePort 31008 (service port 3008)
    upstream order-service {
        server 100.96.54.109:31008;
    }
    server {
        listen 3008;
        location / {
            proxy_pass http://order-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # api-gateway -> k3s NodePort 31007 (service port 3007)
    upstream api-gateway {
        server 100.96.54.109:31007;
    }
    server {
        listen 3007;
        location / {
            proxy_pass http://api-gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # scene-service -> k3s NodePort 31012 (service port 3012)
    upstream scene-service {
        server 100.96.54.109:31012;
    }
    server {
        listen 3012;
        location / {
            proxy_pass http://scene-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # contract-service -> k3s NodePort 31006 (service port 3006)
    upstream contract-service {
        server 100.96.54.109:31006;
    }
    server {
        listen 3006;
        location / {
            proxy_pass http://contract-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    include /etc/nginx/conf.d/*.conf;
}
