events { worker_connections 1024; }
http {
    client_body_timeout 300s;

    client_max_body_size 50m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_connect_timeout 60s;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  server {
    listen 80;
    location /price/ { proxy_pass http://100.96.54.109:31009/; }
    location /assets/ { proxy_pass http://100.96.54.109:31009/assets/; }
    location /api/prices/ { proxy_pass http://100.96.54.109:31009/api/prices/; }
    location /api/raw-flowers/ { proxy_pass http://100.96.54.109:31009/api/raw-flowers/; }
    location / { proxy_pass http://100.96.54.109:8088; }
  }
  server { listen 3001; location / { proxy_pass http://100.96.54.109:31001; } }
  server { listen 3002; location / { proxy_pass http://100.96.54.109:31002; } }
  server { listen 3004; location / { proxy_pass http://100.96.54.109:31004; } }
  server { listen 3005; location / { proxy_pass http://100.96.54.109:31005; } }
  server { listen 3006; location / { proxy_pass http://100.96.54.109:31006; } }
  server { listen 3007; location / { proxy_pass http://100.96.54.109:31007; proxy_set_header x-api-key $http_x_api_key; } }
  server { listen 3008; location / { proxy_pass http://100.96.54.109:31008; } }
  server { listen 3009; location / { proxy_pass http://100.96.54.109:31009; } }
  server { listen 3012; location / { proxy_pass http://100.96.54.109:31012; } }
}
